cabal-version:      3.0
name:               bread-bot
version:            0.1.0.0
synopsis:           A Discord bot for resurfacing bread-reacted messages
description:
  Breadfish recommends memorable Discord posts marked with bread reactions.

category:           Web
license:            MIT
license-file:       LICENSE
author:             Brian Kuhns
maintainer:         Brian Kuhns
build-type:         Simple
extra-source-files: README.md

common shared
  default-language:   Haskell2010
  default-extensions:
    DerivingStrategies
    ImportQualifiedPost
    LambdaCase
    NumericUnderscores
    OverloadedStrings

  ghc-options:
    -Wall -Wcompat -Wincomplete-record-updates
    -Wincomplete-uni-patterns -Wmissing-deriving-strategies

  mixins:
    base hiding (Prelude),
    relude (Relude as Prelude, Relude.Container.One),
    relude

  build-depends:
    , base    >=4.17 && <5
    , relude  >=1.2  && <1.3

library
  import:          shared
  exposed-modules: Bot
  hs-source-dirs:  src
  build-depends:
    , aeson            >=2.2  && <2.3
    , containers       >=0.6  && <0.8
    , discord-haskell  >=1.18 && <1.19
    , random           >=1.2  && <1.3
    , stm              >=2.5  && <2.6
    , text             >=2.1  && <2.2
    , time             >=1.12 && <1.13

executable bread-bot
  import:         shared
  main-is:        Main.hs
  hs-source-dirs: app
  build-depends:
    , bread-bot
    , discord-haskell  >=1.18 && <1.19
    , text             >=2.1  && <2.2

test-suite bread-bot-test
  import:         shared
  type:           exitcode-stdio-1.0
  main-is:        Spec.hs
  hs-source-dirs: test
  ghc-options:    -threaded -rtsopts -with-rtsopts=-N
  build-depends:
    , bread-bot
    , discord-haskell  >=1.18 && <1.19
    , hspec            >=2.11 && <2.12
